[package]
name = "painting"
version = "0.1.0"
authors = ["krystian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.23.0"
imageproc="0.20"
random = { path = "../random" }