[package]
name = "common"
version = "0.1.0"
authors = ["deszczowy"]
edition = "2018"
description = "Things widely used throught all projects"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.52"
